#Importing Required Library  for data cleaning

In [ ]:
import pandas as pd
import numpy as np

## reading the data from excel file

In [ ]:
btech_ganda_data=pd.read_excel('/content/all_btech_data (1).xlsx')

### Getting an overview of data

In [ ]:
len(btech_ganda_data.columns)

29

In [ ]:
btech_ganda_data.columns

Index(['SID', 'COURSE', 'NAME', 'Age', 'Sex', 'State', 'Father's Business',
       'Mother's Business', 'Number of brothers', 'Numebr of sisters',
       'Joint Family?', 'Family Size', 'Family Income', 'Rank JEE',
       'Latest CGPA', '12th grades', 'Higher study?', 'Dropped?', 'TEACHING',
       'INFRA', 'SPORTS', 'HOSTEL', 'How know?', 'CELL PHONE', 'STUDY',
       'EXTRA', 'CO', 'CHATTING', 'SLEEPING'],
      dtype='object')

In [ ]:
btech_ganda_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 202 entries, 0 to 201
Data columns (total 29 columns):
 #   Column              Non-Null Count  Dtype 
---  ------              --------------  ----- 
 0   SID                 199 non-null    object
 1   COURSE              4 non-null      object
 2   NAME                12 non-null     object
 3   Age                 202 non-null    int64 
 4   Sex                 202 non-null    object
 5   State               202 non-null    object
 6   Father's Business   197 non-null    object
 7   Mother's Business   198 non-null    object
 8   Number of brothers  199 non-null    object
 9   Numebr of sisters   193 non-null    object
 10  Joint Family?       200 non-null    object
 11  Family Size         201 non-null    object
 12  Family Income       163 non-null    object
 13  Rank JEE            181 non-null    object
 14  Latest CGPA         157 non-null    object
 15  12th grades         194 non-null    object
 16  Higher study?       201 no

## Dropping Two Columns named as COURSE and NAME as they have a lot of NULL values and are not of any relevance for making any analysis

In [ ]:
btech_ganda_data=btech_ganda_data.drop('COURSE',axis=1)

In [ ]:
btech_ganda_data=btech_ganda_data.drop('NAME',axis=1)

In [ ]:
btech_ganda_data

SID  Age     Sex     State Father's Business Mother's Business  \
0            0   18       M       GUJ          Business        Home maker   
1    202301025   19       M       GUJ               Job        Home maker   
2    202201506   19       M       GUJ         Principal        Home maker   
3    202101146   21       M       GUJ            farmer        Home maker   
4    202401139   17  Female  Gujarat      Govt Service         Housewife    
..         ...  ...     ...       ...               ...               ...   
197  202101510   19  Female   Gujarat    Government job         Homemaker   
198  202401075   18    MALE   Gujarat          Business        House wife   
199  202303031   19    MALE   GUJARAT      Head Teacher         Housewife   
200  202201145   20    MALE   Gujarat       Businessman        House wife   
201  202101097   21    MALE   Gujarat               Job        House wife   

    Number of brothers Numebr of sisters Joint Family? Family Size  ... INFRA  \
0                    1                 0       Nuclear           4  ...     2   
1                    0                 0       Nuclear           3  ...     2   
2                    0                 0       Nuclear           3  ...     1   
3                    1                 0         Joint           8  ...     2   
4                    1                 2         Joint           6  ...     2   
..                 ...               ...           ...         ...  ...   ...   
197                  0                 1       Nuclear           4  ...     2   
198                  0                 1       Nuclear           4  ...     1   
199                  0                 0         Joint           5  ...     2   
200                  1                 0         Joint           7  ...     2   
201                  0                 1       Nuclear           4  ...     3   

    SPORTS HOSTEL                  How know?         CELL PHONE      STUDY  \
0        2      3                    friends                  2          5   
1        2      2               Social Media                  4          3   
2        1      2               Social Media                  6          6   
3        3      1                    Teacher                  3          5   
4        2      2                    Teacher                  5          7   
..     ...    ...                        ...                ...        ...   
197      2    NaN          Friends or Family  More than 4 hours  1-2 hours   
198      2      3  While searching on Google                  6          3   
199      2      2    Through Coaching centre                  2          6   
200      4      4                     Alumni                  2          2   
201      3      4                    Friends                  5          3   

                EXTRA                CO   CHATTING           SLEEPING  
0                 NaN                 0          1                  8  
1                 NaN                 2        0.5                  7  
2                 NaN                 1          1                  8  
3                 NaN                 0        0.5                  6  
4                 NaN                 2          1                  6  
..                ...               ...        ...                ...  
197  Less than 1 hour  Less than 1 hour  1-2 hours  More than 8 hours  
198                 0                 2          3                  9  
199                 1                 0          2                  7  
200                 2                 1          1                  7  
201                 2                 3          2                  8  

[202 rows x 27 columns]

# Cleaning the feature of SEX and making it in two catergory representing M for Male and F for Female

In [ ]:
btech_ganda_data['Sex'].unique()

array(['M', 'Female', 'Male', 'MALE', 'F', 'Malw', 'female ', 'male ',
       'Male ', 'male'], dtype=object)

In [ ]:
btech_ganda_data['Sex']=btech_ganda_data['Sex'].replace(r'^M.*|^m.*','M',regex=True)

In [ ]:
btech_ganda_data['Sex']=btech_ganda_data['Sex'].replace(r'^F.*|^f.*','F',regex=True)

In [ ]:
btech_ganda_data['Sex'].unique()

array(['M', 'F'], dtype=object)

# Now Cleaning the state feature and setting all the state name with their abbrivation

In [ ]:
btech_ganda_data['State'].unique()

array(['GUJ', 'Gujarat ', 'Gujarat', 'Gujrat', 'Maharashtra', 'Delhi',
       'Gujrat ', 'Rajasthan', 'Telangana', 'Madhya Pradesh ',
       'Utter pradesh', 'Uttar Pradesh', 'Guajarat', 'Gujurat',
       'Andhra Pradesh ', 'gujarat', 'Karnataka', 'Rajasthan ',
       'Maharastra', 'Uttar Pradesg', 'rajasthan', 'delhi', 'kerala',
       'Karnataka ', 'Tripura', 'Madhya Pradesh', 'GUJARAT'], dtype=object)

In [ ]:
btech_ganda_data['State']=btech_ganda_data['State'].replace(r'^G.*|^g.*','GJ',regex=True)

In [ ]:
btech_ganda_data['State']=btech_ganda_data['State'].replace(r'^D.*|^d.*','DL',regex=True)

In [ ]:
btech_ganda_data['State']=btech_ganda_data['State'].replace(r'^U.*|^u.*','UP',regex=True)


In [ ]:
btech_ganda_data['State']=btech_ganda_data['State'].replace(r'^Mah.*','MH',regex=True)

In [ ]:
btech_ganda_data['State']=btech_ganda_data['State'].replace(r'^Mad.*','MP',regex=True)

In [ ]:
btech_ganda_data['State']=btech_ganda_data['State'].replace(r'^R.*|^r.*','RJ',regex=True)

In [ ]:
btech_ganda_data['State']=btech_ganda_data['State'].replace(r'^An.*','AP',regex=True)

In [ ]:
btech_ganda_data['State']=btech_ganda_data['State'].replace(r'^Ka.*','KA',regex=True)

In [ ]:
btech_ganda_data['State']=btech_ganda_data['State'].replace(r'^ke.*','KL',regex=True)

In [ ]:
btech_ganda_data['State']=btech_ganda_data['State'].replace(r'^Te.*','TG',regex=True)

In [ ]:
btech_ganda_data['State']=btech_ganda_data['State'].replace(r'^Tr.*','TR',regex=True)

In [ ]:
btech_ganda_data['State'].unique()

array(['GJ', 'MH', 'DL', 'RJ', 'TG', 'MP', 'UP', 'AP', 'KA', 'KL', 'TR'],
      dtype=object)

# Analysisng using bar Chart that which state students are more on campus

In [ ]:
import plotly.express as px
fig = px.histogram(btech_ganda_data, x="State")
fig.show()

# Using Bar chart exploring what is the gender proportions on campus
### from the chart we can infer that their are around 4 men per girl DAIICT campus

In [ ]:
import plotly.express as px
fig = px.histogram(btech_ganda_data, x="Sex")
fig.show()

In [ ]:
btech_ganda_data.columns

Index(['SID', 'Age', 'Sex', 'State', 'Father's Business', 'Mother's Business',
       'Number of brothers', 'Numebr of sisters', 'Joint Family?',
       'Family Size', 'Family Income', 'Rank JEE', 'Latest CGPA',
       '12th grades', 'Higher study?', 'Dropped?', 'TEACHING', 'INFRA',
       'SPORTS', 'HOSTEL', 'How know?', 'CELL PHONE', 'STUDY', 'EXTRA', 'CO',
       'CHATTING', 'SLEEPING'],
      dtype='object')

# Now Cleaning the feature of Higher studies which should have two categories yes or now but in uncleaned data it have many differnet words representing the same thing

In [ ]:
btech_ganda_data['Higher study?'].value_counts()

Higher study?
No                            110
Yes                            49
Maybe                          16
no                              8
yes                             4
NO                              4
Have not thought about it!      3
no                              3
YES                             3
Not Yet Decided                 1
Name: count, dtype: int64

In [ ]:
btech_ganda_data['Higher study?']=btech_ganda_data['Higher study?'].replace(r'^N.*|^n.*','N',regex=True)

In [ ]:
btech_ganda_data['Higher study?']=btech_ganda_data['Higher study?'].replace(r'^Y.*|^y.*','Y',regex=True)

In [ ]:
btech_ganda_data['Higher study?']=btech_ganda_data['Higher study?'].replace(r'^H.*','Maybe',regex=True)

In [ ]:
btech_ganda_data['Higher study?'].value_counts()

Higher study?
N        126
Y         56
Maybe     19
Name: count, dtype: int64

# Again using the Bar Graph we can figure out that on campus how many students want to pursure higher studies and how many don't and how many student still haven't decided

In [ ]:
import plotly.express as px
fig = px.histogram(btech_ganda_data, x="Higher study?",nbins=40)
fig.update_layout(bargap=0.6)
fig.show()

In [ ]:
btech_ganda_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 202 entries, 0 to 201
Data columns (total 27 columns):
 #   Column              Non-Null Count  Dtype 
---  ------              --------------  ----- 
 0   SID                 199 non-null    object
 1   Age                 202 non-null    int64 
 2   Sex                 202 non-null    object
 3   State               202 non-null    object
 4   Father's Business   197 non-null    object
 5   Mother's Business   198 non-null    object
 6   Number of brothers  199 non-null    object
 7   Numebr of sisters   193 non-null    object
 8   Joint Family?       200 non-null    object
 9   Family Size         201 non-null    object
 10  Family Income       163 non-null    object
 11  Rank JEE            181 non-null    object
 12  Latest CGPA         157 non-null    object
 13  12th grades         194 non-null    object
 14  Higher study?       201 non-null    object
 15  Dropped?            198 non-null    object
 16  TEACHING            198 no

# Now Cleaning another feature named as dropped wether they have taken drop for preperation or not even this is a categorical feature which should have only two values either yes or NO

In [ ]:
btech_ganda_data['Dropped?'].value_counts()

Dropped?
No     164
no      14
Yes     11
NO       6
YES      2
yes      1
Name: count, dtype: int64

In [ ]:
btech_ganda_data['Dropped?']=btech_ganda_data['Dropped?'].replace(r'^N.*|^n.*','No',regex=True)

In [ ]:
btech_ganda_data['Dropped?']=btech_ganda_data['Dropped?'].replace(r'^Y.*|^y.*','Yes',regex=True)

# Plotting the Bar Graph we can observe that among btech student most of them have not taken a Drop for preperation of any competitive exams

In [ ]:
fig = px.histogram(btech_ganda_data, x="Dropped?",nbins=40)
fig.update_layout(bargap=0.6)
fig.show()

# Now Cleaning the feature which says wheather a Btech Student is from join family ot not


In [ ]:
btech_ganda_data['Joint Family?'].unique()

array(['Nuclear', 'Joint', 'Nuclear Family', 'Joint Family',
       'Nuclear family', 'Joint family', 'nuclear', 'joint', nan,
       'Nuclear (Parents and Children)', 'nuclear family',
       'Nuclear Family (Separate)', 'NUCLEAR', 'joint family', 5, 3, 6, 4],
      dtype=object)

# Observing the unique data their are input like 5,3,4,6 so to clean such input we just write a snippite which detech numbers and convert it to join as in genral at DAIICT campus most of the student belongs to nuclear families and a very few belong to joint famiy so just to make a distribution a bit equal we just put all the numeric values as the joint family section

In [ ]:

for i in btech_ganda_data['Joint Family?']:
  if type(i) is int:
    btech_ganda_data['Joint Family?']=btech_ganda_data['Joint Family?'].replace(i,'Joint',regex=True)

In [ ]:
btech_ganda_data['Joint Family?']=btech_ganda_data['Joint Family?'].replace(r'^3.*','Joint',regex=True)

In [ ]:
btech_ganda_data['Joint Family?']=btech_ganda_data['Joint Family?'].replace(r'^N.*|^n.*','Nuclear',regex=True)

In [ ]:
btech_ganda_data['Joint Family?']=btech_ganda_data['Joint Family?'].replace(r'^J.*|^j.*','Joint',regex=True)

In [ ]:
btech_ganda_data['Joint Family?']=btech_ganda_data['Joint Family?'].fillna('Prefer Not To say')

In [ ]:
btech_ganda_data['Joint Family?'].unique()

array(['Nuclear', 'Joint', 'Prefer Not To say'], dtype=object)

# Plotting a bar graph which shows how many student at DAIICT belongs to Joint Family and how many belongs to Nuclear it also has a small proportion which are not comfotable to talk about their family size the just where not willing to share

In [ ]:
fig = px.histogram(btech_ganda_data, x="Joint Family?",nbins=40)
fig.update_layout(bargap=0.6)
fig.show()

# Cleaning the Family income making bins on the basis of income like below 5 lacs between 5 and 10 lacs and so on

In [ ]:
btech_ganda_data['Family Income'].unique()

array([0, 8, 400000, 2000000, 1000000, 600000, 0.95, nan, 10, 5, 6, 2.1,
       200000, 12, 1, 250000, 1800000, 1600000, 2100000, 11, '00', 450000,
       '>10', '8 lacs', 650000, 920000, '6 LPA', '60 LPA', '11 LPA',
       '10 LPA', 700000, 950000, 750000, 1100000, 350000, 800000, 150000,
       120000, 2, 'Less than 10', 'More than 10', 'less than 10', 15,
       'Not prefer to say', '5 lpa', 'Above 6 lpa', 1.5, 1650000, 40000,
       500000, 4, 40, 28, '<=12', '>=12', '>=6', '8,00,000',
       'Greater than 10 Lakh per annum ', 100000, '4 lakh ', '5 lakh',
       180000, 'Less than 2 lakh', 'Below 9 lakh', 70, 30, 18, 50000, '.',
       '>400000', '<5 lakh', 300000, 80000, '-', '15LPA', 'Not to say',
       '7LPA', '10LPA', '15 Lakh', '12 Lakh', '6 Lakh', '8 Lakh', 1200000,
       1500000, 'more than 20 lakh', '10-20 lakh', '2.5-5 lakh',
       '10 lakh', '86k per month ', '10lakh',
       999999999999999993220948674361627976461708441944064, 160000,
       5000000, '8-9 lakh', 'Belo

In [ ]:

pd.set_option('display.max_rows', None)
btech_ganda_data['Family Income'].value_counts()

Family Income
0                                                      10
10                                                      6
8                                                       5
400000                                                  5
1000000                                                 5
600000                                                  4
Below 9 lakh                                            4
800000                                                  4
15                                                      4
300000                                                  4
200000                                                  4
150000                                                  3
2                                                       3
5                                                       3
12                                                      3
30                                                      2
250000                                                  2
120000                                                  2
2000000                                                 2
6                                                       2
more than 20 lakh                                       2
10-20 lakh                                              2
1.5                                                     2
500000                                                  2
Less than 10                                            2
5000000                                                 2
70                                                      1
80000                                                   1
<5 lakh                                                 1
-                                                       1
15LPA                                                   1
Not to say                                              1
>400000                                                 1
7LPA                                                    1
10LPA                                                   1
.                                                       1
50000                                                   1
18                                                      1
1200000                                                 1
15 Lakh                                                 1
12 Lakh                                                 1
2024-04-05 00:00:00                                     1
2024-10-15 00:00:00                                     1
Above 12lakhs                                           1
14-15 lakh annum                                        1
12 lac                                                  1
Below 3lakh                                             1
8-9 lakh                                                1
160000                                                  1
999999999999999993220948674361627976461708441944064     1
10lakh                                                  1
86k per month                                           1
10 lakh                                                 1
2.5-5 lakh                                              1
1500000                                                 1
180000                                                  1
8 Lakh                                                  1
6 Lakh                                                  1
Less than 2 lakh                                        1
40                                                      1
5 lakh                                                  1
4 lakh                                                  1
10 LPA                                                  1
11 LPA                                                  1
60 LPA                                                  1
6 LPA                                                   1
920000                                                  1
650000                                                  1
8 lacs                                    

# This Feature have a lot of ambiguous data where some like some have entered the income in string format some in number while some have added with comman and some have with spaces so to make it a bit uniform we are simply converting all non digit character to white spaces using regex

In [ ]:
import pandas as pd
import re


df = pd.DataFrame(btech_ganda_data['Family Income'])


def remove_strings(val):
    if isinstance(val, str):
        # Use regex to replace all non-digit characters with an empty string
        return re.sub(r'\D+', ' ', val)  # \D matches any non-digit character
    return val  # Return as is if it's not a string

# Apply the function to the DataFrame column
df['Family Income'] = df['Family Income'].apply(remove_strings)



In [ ]:
df['Family Income'].unique()

array([0, 8, 400000, 2000000, 1000000, 600000, 0.95, nan, 10, 5, 6, 2.1,
       200000, 12, 1, 250000, 1800000, 1600000, 2100000, 11, '00', 450000,
       ' 10', '8 ', 650000, 920000, '6 ', '60 ', '11 ', '10 ', 700000,
       950000, 750000, 1100000, 350000, 800000, 150000, 120000, 2, 15,
       ' ', '5 ', ' 6 ', 1.5, 1650000, 40000, 500000, 4, 40, 28, ' 12',
       ' 6', '8 00 000', ' 10 ', 100000, '4 ', 180000, ' 2 ', ' 9 ', 70,
       30, 18, 50000, ' 400000', ' 5 ', 300000, 80000, '15 ', '7 ', '12 ',
       1200000, 1500000, ' 20 ', '10 20 ', '2 5 5 ', '86 ',
       999999999999999993220948674361627976461708441944064, 160000,
       5000000, '8 9 ', ' 3 ', '14 15 ', ' 12 ',
       datetime.datetime(2024, 10, 15, 0, 0),
       datetime.datetime(2024, 4, 5, 0, 0), 20], dtype=object)

# We found that some people have entered number like 0 or 00 or space in place of family income we are assuming that these people are not comfortable sharing their family income so making a category for such people named as 'Prefer not to say'

In [ ]:
from datetime import datetime
for i in df['Family Income']:
  if i==' ' or i==00 or i==0  or type(i)==datetime or len(str(i))>10:

    df['Family Income']=df['Family Income'].replace(i,'PreferNotTosay')

In [ ]:
df['Family Income'].unique()

array(['PreferNotTosay', 8, 400000, 2000000, 1000000, 600000, 0.95, nan,
       10, 5, 6, 2.1, 200000, 12, 1, 250000, 1800000, 1600000, 2100000,
       11, '00', 450000, ' 10', '8 ', 650000, 920000, '6 ', '60 ', '11 ',
       '10 ', 700000, 950000, 750000, 1100000, 350000, 800000, 150000,
       120000, 2, 15, '5 ', ' 6 ', 1.5, 1650000, 40000, 500000, 4, 40, 28,
       ' 12', ' 6', '8 00 000', ' 10 ', 100000, '4 ', 180000, ' 2 ',
       ' 9 ', 70, 30, 18, 50000, ' 400000', ' 5 ', 300000, 80000, '15 ',
       '7 ', '12 ', 1200000, 1500000, ' 20 ', '10 20 ', '2 5 5 ', '86 ',
       160000, 5000000, '8 9 ', ' 3 ', '14 15 ', ' 12 ', 20], dtype=object)

# This is a REgex Which replaces the spaces between number and make it one as some people might have added their salary as 10 15 represnting salary between 10 to 15 lcs

In [ ]:

# Function to remove spaces between numbers
def remove_spaces(val):
    if isinstance(val, str):
        # Use regex to remove spaces between numbers
        return re.sub(r'\s+', '', val)  # Replace one or more spaces with an empty string
    return val  # Return as is if it's not a string

# Apply the function to the DataFrame column
df['Family Income'] = df['Family Income'].apply(remove_spaces)

df['Family Income'].unique()


array(['PreferNotTosay', 8, 400000, 2000000, 1000000, 600000, 0.95, nan,
       10, 5, 6, 2.1, 200000, 12, 1, 250000, 1800000, 1600000, 2100000,
       11, '00', 450000, '10', '8', 650000, 920000, '6', '60', '11',
       700000, 950000, 750000, 1100000, 350000, 800000, 150000, 120000, 2,
       15, '5', 1.5, 1650000, 40000, 500000, 4, 40, 28, '12', '800000',
       100000, '4', 180000, '2', '9', 70, 30, 18, 50000, '400000', 300000,
       80000, '15', '7', 1200000, 1500000, '20', '1020', '255', '86',
       160000, 5000000, '89', '3', '1415', 20], dtype=object)

In [ ]:
# Bins for below 5 lacs -> 500000,400000,300000,200000,100000,1,2,3,4,5

# Manually picking all the possible salaries and placing it in a list and then replacing it with a bin called as Less than 5 lacs

In [ ]:
for i in df['Family Income']:
  if i in [1,2,3,4,5,100000,200000,500000,180000,150000,120000,400000,40000,350000,'400000',450000,300000,'255',250000,1.5,'5','2','3','4',2.1,'00']:
    df['Family Income']=df['Family Income'].replace(i,'Less Than 5 Lacs')

In [ ]:
df['Family Income'].unique()

array(['PreferNotTosay', 8, 'Less Than 5 Lacs', 2000000, 1000000, 600000,
       0.95, nan, 10, 6, 12, 1800000, 1600000, 2100000, 11, '10', '8',
       650000, 920000, '6', '60', '11', 700000, 950000, 750000, 1100000,
       800000, 15, 1650000, 40, 28, '12', '800000', '9', 70, 30, 18,
       50000, 80000, '15', '7', 1200000, 1500000, '20', '1020', '86',
       160000, 5000000, '89', '1415', 20], dtype=object)

# Making another bin for Family income size between 5 to 10 lacs  and so on in further code

In [ ]:
for i in df['Family Income']:
  if i in [6,7,8,9,10,'9','6','8','1020','86','89','7',600000,700000,800000,'800000',900000,1000000,1020,50000,'10',1000000,750000,950000,920000,650000,80000,89,86]:
    df['Family Income']=df['Family Income'].replace(i,'Between 5 Lacs To 10 Lacs')

In [ ]:
df['Family Income'].unique()

array(['PreferNotTosay', 'Between 5 Lacs To 10 Lacs', 'Less Than 5 Lacs',
       2000000, 0.95, nan, 12, 1800000, 1600000, 2100000, 11, '60', '11',
       1100000, 15, 1650000, 40, 28, '12', 70, 30, 18, '15', 1200000,
       1500000, '20', 160000, 5000000, '1415', 20], dtype=object)

In [ ]:
for i in df['Family Income']:
  if i in [11,12,13,14,15,'11','12','15',1200000,1500000,'1415']:
    df['Family Income']=df['Family Income'].replace(i,'Between 10 Lac to 15 Lacs')

In [ ]:
df['Family Income'].unique()

array(['PreferNotTosay', 'Between 5 Lacs To 10 Lacs', 'Less Than 5 Lacs',
       2000000, 0.95, nan, 'Between 10 Lac to 15 Lacs', 1800000, 1600000,
       2100000, '60', 1100000, 1650000, 40, 28, 70, 30, 18, '20', 160000,
       5000000, 20], dtype=object)

In [ ]:
df['Family Income'] = df['Family Income'].fillna('PreferNotTosay')

In [ ]:
df['Family Income'].unique()

array(['PreferNotTosay', 'Between 5 Lacs To 10 Lacs', 'Less Than 5 Lacs',
       2000000, 0.95, 'Between 10 Lac to 15 Lacs', 1800000, 1600000,
       2100000, '60', 1100000, 1650000, 40, 28, 70, 30, 18, '20', 160000,
       5000000, 20], dtype=object)

In [ ]:
for i in df['Family Income']:

  if i not in ['PreferNotTosay', 'Between 5 Lacs To 10 Lacs', 'Less Than 5 Lacs','Between 10 Lac to 15 Lacs']:
    df['Family Income']=df['Family Income'].replace(i,'Above 15 Lacs')

In [ ]:
df['Family Income'].unique()

array(['PreferNotTosay', 'Between 5 Lacs To 10 Lacs', 'Less Than 5 Lacs',
       'Above 15 Lacs', 'Between 10 Lac to 15 Lacs'], dtype=object)

In [ ]:
btech_ganda_data['Family Income']=df['Family Income']
fig = px.histogram(btech_ganda_data, x="Family Income",nbins=40)
fig.update_layout(bargap=0.6)
fig.show()

# Now Cleaning the Family Size and Observing the size of family DAIICT Btech Students belong to

In [ ]:
btech_ganda_data['Family Size'].unique()

array([4, 3, 8, 6, 7, 5, 16, 9, nan, '10+', 2, '4 person', 'Option 1', 10,
       'Joint', 'Nuclear'], dtype=object)

In [ ]:
btech_ganda_data['Family Size'].value_counts()

Family Size
4           96
3           27
5           26
6           18
7           13
2            7
9            3
Nuclear      3
8            2
16           1
10+          1
4 person     1
Option 1     1
10           1
Joint        1
Name: count, dtype: int64

# Extracting all the cells which have a family size extred in string and manually assigning it a family size

In [ ]:
for i in btech_ganda_data['Family Size']:
  if i=='Nuclear' or i=='Option 1' or i=='4 person':
    btech_ganda_data['Family Size']=btech_ganda_data['Family Size'].replace(i,4)
  if i=='Joint':
    btech_ganda_data['Family Size']=btech_ganda_data['Family Size'].replace(i,7)
  if i=='10+':
    btech_ganda_data['Family Size']=btech_ganda_data['Family Size'].replace(i,10)

btech_ganda_data['Family Size']=btech_ganda_data['Family Size'].fillna(0)

# Plotting the data to see what size Family most of the DAIICT Btech Student belongs to

In [ ]:
fig = px.histogram(btech_ganda_data, x="Family Size",nbins=10)
fig.update_layout(bargap=0.6)
fig.show()

# Now Cleaning the number of sister column

In [ ]:
btech_ganda_data['Numebr of sisters']=btech_ganda_data['Numebr of sisters'].fillna(0)
# Numebr of sisters

In [ ]:
btech_ganda_data['Numebr of sisters'].unique()

array([0, 2, 1, 4, 'others', 3, 'One'], dtype=object)

In [ ]:
btech_ganda_data['Numebr of sisters'] = btech_ganda_data['Numebr of sisters'].replace('One',1)

In [ ]:
btech_ganda_data['Numebr of sisters'] = btech_ganda_data['Numebr of sisters'].replace('others',0)

# Plotting the Graph we found out that most of the student at DAIICT have no sister and the next most frequent bar was with one sister

In [ ]:
fig = px.histogram(btech_ganda_data, x="Numebr of sisters",nbins=10)
fig.update_layout(bargap=0.6)
fig.show()

# Now doing the same for number of brothers

In [ ]:
btech_ganda_data['Number of brothers'].unique()

array([1, 0, 2, nan, 'other'], dtype=object)

In [ ]:
btech_ganda_data['Number of brothers'] = btech_ganda_data['Number of brothers'].fillna(0)

In [ ]:
btech_ganda_data['Number of brothers'] = btech_ganda_data['Number of brothers'].replace('other',0)

In [ ]:
fig = px.histogram(btech_ganda_data, x="Number of brothers",nbins=10)
fig.update_layout(bargap=0.6)
fig.show()

# Cleaning the Rank JEE column which have multiple types of input observing that some people have entered estimated rank while some have not given the column have multiple type of data some are string some are alpha numeric and some are just numeric

In [ ]:
btech_ganda_data['Rank JEE'].unique()

array(['Not Given', 11000, 3362, 100034, 157743, 4754, 9484, 8000, 181092,
       7394, 0, 81430, 5398, 14000, 73523, 16408, 150000, 71000, 50000,
       226000, 11803, 7393, 5917, 10203, 12938, 11922, 9304, 3651, 8694,
       11145, 37000, nan, 3026, '90000+', 8954, 11790, 17300, 11001,
       11322, 11526, 8023, 56000, 16056, 27500, 15480, 1700, 9864, '17k',
       '14.1k', 12000, 126754, 7740, 5429, '.', 7535, 97000, 9636, 3760,
       9662, 80000, 'ACPC', 25000, 22000, 97.2, 30820, 9048,
       'Not prefer to say', 10071, 6192, 18252, 24874, 2396, 3916, 3500,
       45000, 20000, 11732, 96297, 14285, 14421, 13032, 166000, 6889,
       11220, 28705, 9500, 13673, 10978, 11500, 11021, 55000, 13106,
       67345, 30000, 16594, 10000, 1097, 1629, 11158, 10864, 11308, 11999,
       20956, 'Not given', 195606, 16862, 49000, 7189, 6000, 39987, 105,
       5908, 16000, 10218, 14443, 3773, 9363, 9343, 9011, 347, 13500,
       8015, 28000, 4300, 8948, 9634, 7128, 100000, 6556, 6754, '11.6k',


In [ ]:
btech_ganda_data['Rank JEE']=btech_ganda_data['Rank JEE'].fillna(0)

In [ ]:
btech_ganda_data['Rank JEE']=btech_ganda_data['Rank JEE'].replace('Not Given',0)

In [ ]:
btech_ganda_data['Rank JEE']=btech_ganda_data['Rank JEE'].replace(['ACPC','.','Not prefer to say','Not given'],0)

In [ ]:
(btech_ganda_data['Rank JEE']).unique()

array([0, 11000, 3362, 100034, 157743, 4754, 9484, 8000, 181092, 7394,
       81430, 5398, 14000, 73523, 16408, 150000, 71000, 50000, 226000,
       11803, 7393, 5917, 10203, 12938, 11922, 9304, 3651, 8694, 11145,
       37000, 3026, '90000+', 8954, 11790, 17300, 11001, 11322, 11526,
       8023, 56000, 16056, 27500, 15480, 1700, 9864, '17k', '14.1k',
       12000, 126754, 7740, 5429, 7535, 97000, 9636, 3760, 9662, 80000,
       25000, 22000, 97.2, 30820, 9048, 10071, 6192, 18252, 24874, 2396,
       3916, 3500, 45000, 20000, 11732, 96297, 14285, 14421, 13032,
       166000, 6889, 11220, 28705, 9500, 13673, 10978, 11500, 11021,
       55000, 13106, 67345, 30000, 16594, 10000, 1097, 1629, 11158, 10864,
       11308, 11999, 20956, 195606, 16862, 49000, 7189, 6000, 39987, 105,
       5908, 16000, 10218, 14443, 3773, 9363, 9343, 9011, 347, 13500,
       8015, 28000, 4300, 8948, 9634, 7128, 100000, 6556, 6754, '11.6k',
       'Less than 13k', '43,000 (ACPC 134)', 23125, 3266, 5127, 8022,
  

In [ ]:
btech_ganda_data['Rank JEE']=btech_ganda_data['Rank JEE'].replace('90000+',90000)
btech_ganda_data['Rank JEE']=btech_ganda_data['Rank JEE'].replace('17k',17000)
btech_ganda_data['Rank JEE']=btech_ganda_data['Rank JEE'].replace('14.1k',14100)
btech_ganda_data['Rank JEE']=btech_ganda_data['Rank JEE'].replace('11.6k',11600)
btech_ganda_data['Rank JEE']=btech_ganda_data['Rank JEE'].replace('Less than 13k',13000)
btech_ganda_data['Rank JEE']=btech_ganda_data['Rank JEE'].replace('43,000 (ACPC 134)',43000)
btech_ganda_data['Rank JEE']=btech_ganda_data['Rank JEE'].replace('Approx. 30000',30000)
btech_ganda_data['Rank JEE']=btech_ganda_data['Rank JEE'].replace('1.5L',150000)
btech_ganda_data['Rank JEE']=btech_ganda_data['Rank JEE'].replace('97.2',0)
btech_ganda_data['Rank JEE']=btech_ganda_data['Rank JEE'].replace('CRL 65455',65453)
btech_ganda_data['Rank JEE']=btech_ganda_data['Rank JEE'].astype(int)

In [ ]:
btech_ganda_data['Rank JEE'].unique()

array([     0,  11000,   3362, 100034, 157743,   4754,   9484,   8000,
       181092,   7394,  81430,   5398,  14000,  73523,  16408, 150000,
        71000,  50000, 226000,  11803,   7393,   5917,  10203,  12938,
        11922,   9304,   3651,   8694,  11145,  37000,   3026,  90000,
         8954,  11790,  17300,  11001,  11322,  11526,   8023,  56000,
        16056,  27500,  15480,   1700,   9864,  17000,  14100,  12000,
       126754,   7740,   5429,   7535,  97000,   9636,   3760,   9662,
        80000,  25000,  22000,     97,  30820,   9048,  10071,   6192,
        18252,  24874,   2396,   3916,   3500,  45000,  20000,  11732,
        96297,  14285,  14421,  13032, 166000,   6889,  11220,  28705,
         9500,  13673,  10978,  11500,  11021,  55000,  13106,  67345,
        30000,  16594,  10000,   1097,   1629,  11158,  10864,  11308,
        11999,  20956, 195606,  16862,  49000,   7189,   6000,  39987,
          105,   5908,  16000,  10218,  14443,   3773,   9363,   9343,
      

# Similarly Cleaning the 12th Grade column

In [ ]:
btech_ganda_data['12th grades'].unique()

array([0.9931, 92, 0.92, 0.9092, 74, 80, 82, 95, 0.91, 0.97, 0.85, 0.868,
       0.7692, 0.93, 0.936, 69.8, 93, 79, 90, 89, 90.3, 85.07, 86.61,
       0.89, 0.934, 0.9, 84, 88, 71, 99.92, 0.9584, 97.4, '92%(PCM)',
       93.4, 91, 86, "Don't remember percentage was 94.7", 74.33, 590,
       0.9633, 81.5, '93.4℅', 467, 85, 92.3, 0.79, 0.69, 0.8888, 99.72,
       95.33, 98.3, 96, 'A2', 83, 0.8, nan, 81, 94, 99.64, 0.87, 89.8,
       93.07, 64, 96.4, 98.99, 99.81, 99.96, 99.68, 75, 69, 87, 88.88,
       96.21, 95.23, 'No', 'Maybe', 'Yes', 76, 98.32, 77, '.', 'A1',
       '99.96 PR', 0.98, 0.924, 0.95, 96.18, 78, 'A', 0.86, 0.94, 60,
       98.75, 83.38, 91.2, 0.84, 0.935, 81.2, 98, 0.905, 94.5, 83.2, 68,
       92.8, 89.5, 81.67, 97, 87.5, 73, '89 percentage', 78.45, 90.2,
       94.15], dtype=object)

# As Most of the studet have entered data in 0. so converting those to percentage by shifting two zeros to the right bu multiplying by 100


In [ ]:
df = pd.DataFrame(btech_ganda_data['12th grades'])
def shift_decimal(val):
    try:

        num = float(val)
        if 0 < num < 1:
            return num * 100
        elif num >99:
          return 86
        else:
            return num  # Return as is for other numbers
    except ValueError:
        # If val is not a number, return it as is (string)
        return val
df['12th grades']=df['12th grades'].apply(shift_decimal)

df['12th grades'].unique()


array([99.31, 92.  , 90.92, 74.  , 80.  , 82.  , 95.  , 91.  , 97.  ,
       85.  , 86.8 , 76.92, 93.  , 93.6 , 69.8 , 79.  , 90.  , 89.  ,
       90.3 , 85.07, 86.61, 93.4 , 84.  , 88.  , 71.  , 86.  , 95.84,
       97.4 , 94.7 , 74.33, 59.  , 96.33, 81.5 , 46.  , 92.3 , 69.  ,
       88.88, 95.33, 98.3 , 96.  , 81.  , 83.  ,  0.  , 94.  , 87.  ,
       89.8 , 93.07, 64.  , 96.4 , 98.99, 75.  , 88.88, 96.21, 95.23,
       76.  , 98.32, 77.  , 98.  , 92.4 , 96.18, 78.  , 60.  , 98.75,
       83.38, 91.2 , 93.5 , 81.2 , 90.5 , 94.5 , 83.2 , 68.  , 92.8 ,
       89.5 , 81.67, 87.5 , 73.  , 78.45, 90.2 , 94.15])

In [ ]:
btech_ganda_data['12th grades']=df['12th grades']

In [ ]:
for i in btech_ganda_data['12th grades']:
  if type(i)==str:
    print(i)

92%(PCM)
Don't remember percentage was 94.7
93.4℅
A2
No
Maybe
Yes
Yes
.
A1
99.96 PR
A
89 percentage


In [ ]:
btech_ganda_data['12th grades']=btech_ganda_data['12th grades'].replace('92%(PCM)',92)
btech_ganda_data['12th grades']=btech_ganda_data['12th grades'].replace("Don't remember percentage was 94.7",94.7)
btech_ganda_data['12th grades']=btech_ganda_data['12th grades'].replace("93.4℅",93.4)

btech_ganda_data['12th grades']=btech_ganda_data['12th grades'].replace("A2",81)
btech_ganda_data['12th grades']=btech_ganda_data['12th grades'].replace("A1",91)
btech_ganda_data['12th grades']=btech_ganda_data['12th grades'].replace("99.96 PR",85)
btech_ganda_data['12th grades']=btech_ganda_data['12th grades'].replace("A",84)
btech_ganda_data['12th grades']=btech_ganda_data['12th grades'].replace("89 percentage",89)


In [ ]:
btech_ganda_data['12th grades']=btech_ganda_data['12th grades'].replace(590.,59)
btech_ganda_data['12th grades']=btech_ganda_data['12th grades'].replace(467.,46)

In [ ]:
btech_ganda_data['12th grades']=btech_ganda_data['12th grades'].fillna(0)

In [ ]:
btech_ganda_data['12th grades']=btech_ganda_data['12th grades'].replace(['No','Maybe','Yes','Yes','.'],0)

In [ ]:
btech_ganda_data['12th grades'].unique()

array([99.31, 92.  , 90.92, 74.  , 80.  , 82.  , 95.  , 91.  , 97.  ,
       85.  , 86.8 , 76.92, 93.  , 93.6 , 69.8 , 79.  , 90.  , 89.  ,
       90.3 , 85.07, 86.61, 93.4 , 84.  , 88.  , 71.  , 86.  , 95.84,
       97.4 , 94.7 , 74.33, 59.  , 96.33, 81.5 , 46.  , 92.3 , 69.  ,
       88.88, 95.33, 98.3 , 96.  , 81.  , 83.  ,  0.  , 94.  , 87.  ,
       89.8 , 93.07, 64.  , 96.4 , 98.99, 75.  , 88.88, 96.21, 95.23,
       76.  , 98.32, 77.  , 98.  , 92.4 , 96.18, 78.  , 60.  , 98.75,
       83.38, 91.2 , 93.5 , 81.2 , 90.5 , 94.5 , 83.2 , 68.  , 92.8 ,
       89.5 , 81.67, 87.5 , 73.  , 78.45, 90.2 , 94.15])

#Cleaning the Latest CGPA

In [ ]:
btech_ganda_data['Latest CGPA'].unique()
ls=[]
for i in btech_ganda_data['Latest CGPA']:

  if type(i)==str:
    print(i)
    ls.append(i)

.
Not applicable
Nill
.
-
Na
Nil
More than 7.5
Nil
.


In [ ]:
btech_ganda_data['Latest CGPA']=btech_ganda_data['Latest CGPA'].fillna(0)

In [ ]:
btech_ganda_data['Latest CGPA']=btech_ganda_data['Latest CGPA'].replace('More than 7.5',8.2)
btech_ganda_data['Latest CGPA']=btech_ganda_data['Latest CGPA'].replace(ls,0)

In [ ]:

# 94. ,98.  , 87.  , 78.
btech_ganda_data['Latest CGPA']=btech_ganda_data['Latest CGPA'].replace(94.,9.4)
btech_ganda_data['Latest CGPA']=btech_ganda_data['Latest CGPA'].replace(98.,9.8)
btech_ganda_data['Latest CGPA']=btech_ganda_data['Latest CGPA'].replace(87.,8.7)
btech_ganda_data['Latest CGPA']=btech_ganda_data['Latest CGPA'].replace(78.,7.8)

In [ ]:
btech_ganda_data['Latest CGPA'].unique()

array([0.  , 7.5 , 8.86, 7.22, 7.  , 5.86, 9.  , 7.34, 7.29, 6.38, 7.7 ,
       7.62, 6.9 , 7.81, 8.44, 8.24, 8.1 , 8.  , 8.2 , 8.32, 8.43, 5.5 ,
       8.55, 7.2 , 7.4 , 9.29, 7.79, 5.  , 8.3 , 7.8 , 8.11, 6.74, 8.5 ,
       7.12, 6.15, 6.84, 7.9 , 7.15, 5.9 , 7.97, 8.68, 8.87, 6.11, 6.77,
       7.02, 8.64, 6.8 , 6.32, 7.75, 6.65, 6.52, 8.4 , 5.8 , 9.7 , 7.3 ,
       8.76, 9.5 , 6.6 , 8.42, 6.12, 8.9 , 9.35, 7.44, 6.5 , 5.14, 7.6 ,
       6.2 , 7.39, 5.95, 6.02, 8.45, 9.4 , 9.8 , 8.7 , 8.23, 6.  , 8.72,
       9.3 , 8.08, 8.21, 7.63, 7.35, 7.68, 6.96, 7.1 , 7.11, 8.6 , 6.67,
       8.15, 5.46, 8.35, 8.51, 9.05, 7.92, 7.46, 7.99, 7.98, 6.05, 6.95,
       8.84])

In [ ]:
btech_ganda_data.columns
      # 'TEACHING', 'INFRA',
      #  'SPORTS', 'HOSTEL', 'How know?', 'CELL PHONE', 'STUDY', 'EXTRA', 'CO',
      #  'CHATTING', 'SLEEPING'

Index(['SID', 'Age', 'Sex', 'State', 'Father's Business', 'Mother's Business',
       'Number of brothers', 'Numebr of sisters', 'Joint Family?',
       'Family Size', 'Family Income', 'Rank JEE', 'Latest CGPA',
       '12th grades', 'Higher study?', 'Dropped?', 'TEACHING', 'INFRA',
       'SPORTS', 'HOSTEL', 'How know?', 'CELL PHONE', 'STUDY', 'EXTRA', 'CO',
       'CHATTING', 'SLEEPING'],
      dtype='object')

# Cleaning the SID column making a derived attribute of year from this column of SID

In [ ]:
df=pd.DataFrame(btech_ganda_data['SID'])

In [ ]:
for i in btech_ganda_data['SID']:
  if len(str(i))==9:

    df['SID']=df['SID'].replace(i,int(str(i)[0:4]))
  if len(str(i))<9 or len(str(i))>9:
    df['SID']=df['SID'].replace(i,2024)

In [ ]:
btech_ganda_data['SID']=df['SID']

In [ ]:
btech_ganda_data.columns

Index(['SID', 'Age', 'Sex', 'State', 'Father's Business', 'Mother's Business',
       'Number of brothers', 'Numebr of sisters', 'Joint Family?',
       'Family Size', 'Family Income', 'Rank JEE', 'Latest CGPA',
       '12th grades', 'Higher study?', 'Dropped?', 'TEACHING', 'INFRA',
       'SPORTS', 'HOSTEL', 'How know?', 'CELL PHONE', 'STUDY', 'EXTRA', 'CO',
       'CHATTING', 'SLEEPING'],
      dtype='object')

# PLotting SID and finding out that from the data collected it is evenly distributed among all the students

In [ ]:
fig = px.histogram(btech_ganda_data, x="SID",nbins=10)
fig.update_layout(bargap=0.6)
fig.show()

# Further Gathering the cleaned data from class changing my features with the features of cleand data to do more presice EDA

In [ ]:
cleaned_data_=pd.read_csv('/content/btechcleaned.csv')
pd.set_option("display.max_columns", None)

In [ ]:
btech_ganda_data["Father's Business"]=cleaned_data_["Father's Business"]
btech_ganda_data["Mother's Business"]=cleaned_data_["Mother's Business"]
btech_ganda_data["How know?"]=cleaned_data_["How know?"]


In [ ]:
btech_ganda_data["CELL PHONE"]=cleaned_data_["CELL PHONE"]
btech_ganda_data["STUDY"]=cleaned_data_["STUDY"]
btech_ganda_data["SLEEPING"]=cleaned_data_["SLEEPING"]

In [ ]:
btech_ganda_data["TEACHING"]=cleaned_data_["TEACHING"]
btech_ganda_data["INFRA"]=cleaned_data_["INFRA"]
btech_ganda_data["SPORTS"]=cleaned_data_["SPORTS"]
btech_ganda_data["HOSTEL"]=cleaned_data_["HOSTEL"]


In [ ]:
btech_ganda_data=btech_ganda_data.drop('CO', axis=1)

In [ ]:
btech_ganda_data=btech_ganda_data.drop('EXTRA', axis=1)

In [ ]:
btech_ganad_data=btech_ganda_data['TEACHING'].fillna("Not Given")

In [ ]:
btech_ganda_data.columns

Index(['SID', 'Age', 'Sex', 'State', 'Father's Business', 'Mother's Business',
       'Number of brothers', 'Numebr of sisters', 'Joint Family?',
       'Family Size', 'Family Income', 'Rank JEE', 'Latest CGPA',
       '12th grades', 'Higher study?', 'Dropped?', 'TEACHING', 'INFRA',
       'SPORTS', 'HOSTEL', 'How know?', 'CELL PHONE', 'STUDY', 'CHATTING',
       'SLEEPING'],
      dtype='object')

In [ ]:
import plotly.express as px
df=btech_ganda_data[btech_ganda_data['12th grades']>0]
fig = px.box(df, x="State", y="12th grades", color="Sex")
fig.update_traces(quartilemethod="exclusive")
fig.show()

In [ ]:
import plotly.express as px
df=btech_ganda_data[btech_ganda_data['Rank JEE']>0]
fig = px.box(df, x="State", y="Rank JEE", color="Sex")
fig.update_traces(quartilemethod="exclusive")
fig.show()

In [ ]:
import plotly.express as px
fig = px.box(df, x="Family Income", y="12th grades", color="Sex")
fig.update_traces(quartilemethod="exclusive") # or "inclusive", or "linear" by default
fig.show()

In [ ]:
import plotly.express as px
fig = px.box(df, x="Family Income", y="Rank JEE", color="Sex")
fig.update_traces(quartilemethod="exclusive") # or "inclusive", or "linear" by default
fig.show()

In [ ]:
import plotly.express as px
df=btech_ganda_data[btech_ganda_data['Latest CGPA']>0]

fig = px.scatter(df, x="Latest CGPA", y="12th grades", color="Sex",
                )
fig.show()

In [ ]:
import plotly.express as px
df=btech_ganda_data[btech_ganda_data['Latest CGPA']>0]

fig = px.scatter(df, x="Latest CGPA", y="12th grades", color="Family Income",
                )
fig.show()

In [ ]:
df.columns

Index(['SID', 'Age', 'Sex', 'State', 'Father's Business', 'Mother's Business',
       'Number of brothers', 'Numebr of sisters', 'Joint Family?',
       'Family Size', 'Family Income', 'Rank JEE', 'Latest CGPA',
       '12th grades', 'Higher study?', 'Dropped?', 'TEACHING', 'INFRA',
       'SPORTS', 'HOSTEL', 'How know?', 'CELL PHONE', 'STUDY', 'CHATTING',
       'SLEEPING'],
      dtype='object')

In [ ]:
import plotly.express as px
df=btech_ganda_data[btech_ganda_data['Latest CGPA']>0]

fig = px.scatter(df, x="Latest CGPA", y="12th grades", color="Joint Family?",
                )
fig.show()